### ISSUE TITLE
Has Noto Sans glyphs

### ISSUE THREAD

**Issue by DLasher106** [notofonts/ottoman-siyaq-numbers#3]
The full version of Noto Serif Ottoman Siyaq Numbers has glyphs from the Noto Sans font (wrong `includeSubsets` in config.yaml?).

**Comment by eliheuer** [comment]
@simoncozens This is a problem we ran into while doing the new classification work in 2023.

I made a new issue here with screenshots: https://github.com/notofonts/ottoman-siyaq-numbers/issues/4
